version: "3.7"
services:
  backend:
    build: backend
    restart: always
    ports: 
      - '8004:8004'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8004/api/v1/auth/login || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
